apiVersion: eksctl.io/v1alpha5
availabilityZones:
  - ap-southeast-1b
  - ap-southeast-1c
  - ap-southeast-1a
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
fargateProfiles:
  - name: defaultfp
    selectors:
      - namespace: default
      - namespace: kube-system
    status: ""
iam:
  vpcResourceControllerPolicy: true
  withOIDC: true
kind: ClusterConfig
kubernetesNetworkConfig:
  ipFamily: IPv4
metadata:
  name: ootb-cluster
  region: ap-southeast-1
  version: "1.22"
privateCluster:
  enabled: false
  skipEndpointCreation: false
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single
